export { default as getDiffInMilliseconds } from './getDiffInMilliseconds.js';
export { default as getDiffInCalendarSeconds } from './getDiffInCalendarSeconds.js';
export { default as getDiffInCalendarMinutes } from './getDiffInCalendarMinutes.js';
export { default as getDiffInCalendarHours } from './getDiffInCalendarHours.js';
export { default as getDiffInCalendarDays } from './getDiffInCalendarDays.js';
export { default as getDiffInCalendarWeeks } from './getDiffInCalendarWeeks.js';
export { default as getDiffInCalendarMonths } from './getDiffInCalendarMonths.js';
export { default as getDiffInCalendarQuarters } from './getDiffInCalendarQuarters.js';
export { default as getDiffInCalendarYears } from './getDiffInCalendarYears.js';
